pf4 bookmarks dropdown
SatelliteQE/airgun pull request #1200
Opened 2024-01-25 09:41 UTC by pondrejk

This change fixes around 90 tests in the bookmark component. The locator for bookmarks dropdown was not accurate for pf4 searchboxes, plus views were not updated to use pf4 search. The remaining legacy searchboxes continue to work.

Test result for component with pf4 searcbox:
```
 pytest tests/foreman/ui/test_bookmarks.py -k  test_positive_end_to_end[Architecture]
=============================================== test session starts ===============================================                                                               

tests/foreman/ui/test_bookmarks.py .
```

Page with legacy searchbox:
```

pytest tests/foreman/ui/test_bookmarks.py -k  test_positive_end_to_end[product]
=============================================== test session starts ===============================================                                                               

tests/foreman/ui/test_bookmarks.py .
```

2024-01-30 11:59 UTC, omkarkhatavkar commented on airgun/widgets.py
> +    actions = ActionsDropdown("//div[contains(@data-ouia-component-id, 'bookmarks-dropdown')]")
Nice !

2024-01-30 12:00 UTC, omkarkhatavkar commented on airgun/widgets.py
> +    pf4_drop_down = Text("//div[contains(@data-ouia-component-id, 'bookmarks-dropdown')]")
Good !

2024-01-30 13:13 UTC, omkarkhatavkar requested changes
I think better to avoid adding extra variable is all are those coming from the `SearchableViewMixinPF4`. Apart from that looks solid

2024-01-30 15:17 UTC, pondrejk commented
thanks @omkarkhatavkar, I didn't realize there is inheritance, updated

2024-01-31 09:47 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_bookmarks.py -k test_positive_end_to_end

2024-01-31 13:30 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_bookmarks.py -k test_positive_end_to_end

2024-01-31 17:03 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_bookmarks.py -k test_positive_end_to_end

2024-02-01 09:45 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_bookmarks.py -k test_positive_end_to_end

2024-02-01 15:14 UTC, omkarkhatavkar approved these changes

2024-02-01 15:15 UTC, omkarkhatavkar commented
@pondrejk Almost everything looks okay, there 1-2 cases missing for search. but other failures seem are unrelated to search

2024-02-06 09:15 UTC, pondrejk commented
@omkarkhatavkar thank you, I updated the package view that shouldn't have been changed, the other failures need to be fixed on the robottelo side, I'll make a pr soon

2024-02-06 09:41 UTC, omkarkhatavkar commented
@pondrejk I don't want to wait more time for 1 more reviewer. This looks good I will merge your PR. We need to have more participation from reviewers.

2024-02-06 09:42 UTC, merged

2024-03-19 12:57 UTC, dosas commented on airgun/views/repository.py
> +class RepositoriesView(BaseLoggedInView, SearchableViewMixinPF4):
@pondrejk Is foreman 3.9 (katello 4.11.1) (6.15.z) really using this? For me this breaks some of the following tests:

```
tests/foreman/ui/test_repository.py
```