changes to fetch the config report data
SatelliteQE/airgun pull request #1479
Opened 2024-07-26 08:46 UTC by amolpati30

Written some entities and views to schedule the Ansible job and fetch data from the configuration report log.

Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15770

2024-07-26 12:03 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_ansible_config_report_changes_notice_and_failed_tasks_errors
robottelo: 15770

2024-07-31 04:55 UTC, omkarkhatavkar requested changes

2024-07-31 04:55 UTC, omkarkhatavkar commented on airgun/entities/host_new.py
> +from selenium.webdriver.common.by import By
No direct selenium imports

2024-08-14 06:21 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_ansible_config_report_changes_notice_and_failed_tasks_errors
robottelo: 15770

2024-08-14 07:13 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 345
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_ansible_config_report_changes_notice_and_failed_tasks_errors --external-logging
Test Result : ========== 1 passed, 17 deselected, 38 warnings in 2764.55s (0:46:04) ==========
```

2024-08-14 07:50 UTC, amolpati30 commented on airgun/entities/host_new.py
> +from selenium.webdriver.common.by import By
Removed this part

2024-08-14 12:12 UTC, omkarkhatavkar commented on airgun/entities/activationkey.py
> +        view.repository_sets.actions.fill('Override to Enabled')
why fill not working for you ? Can you please override that if that is not working for you ?

2024-08-14 12:15 UTC, omkarkhatavkar approved these changes
ACK, Overall looks good. One minor change

2024-08-14 14:17 UTC, Gauravtalreja1 approved these changes

2024-08-14 17:05 UTC, omkarkhatavkar approved these changes

2024-08-14 17:05 UTC, merged