fix the locator issue in action drop down
SatelliteQE/airgun pull request #716
Opened 2022-06-20 10:28 UTC by omkarkhatavkar

- Remove the redundant `self.open`
- Fixed the correct locator here (https://github.com/SatelliteQE/airgun/pull/711/files#diff-b6d36691d2c9b246c1a2f7fff90473fe0098b4a6846694417e9acc246e35ea30R569) because of this line commit  

@vsedmik Can you please test your changes as well 1 bookmark test passes with this change.

2022-06-20 12:14 UTC, vsedmik approved these changes
Tested with tests/foreman/ui/test_smartclassparameter.py::test_positive_update_matcher_from_attribute and it passed, so seems good to me.

2022-06-20 13:23 UTC, peterdragun requested changes

2022-06-20 13:23 UTC, peterdragun commented on airgun/widgets.py
> -            self.open()
Please leave this open as this will be necessary after merging #715

2022-06-20 14:41 UTC, peterdragun approved these changes

2022-06-23 02:24 UTC, omkarkhatavkar commented
merging this as multiple ack's

2022-06-23 02:25 UTC, merged