adding new functionality for verify checksum
SatelliteQE/airgun pull request #721
Opened 2022-07-06 20:22 UTC by ColeHiggins2

Adding functionality to Verify Content Checksum

2022-07-11 14:15 UTC, latran commented on airgun/entities/product.py
> +
You're missing the portion where you need to search for the product name and then selecting it.  Here's a sample code to get you started from `common.py` that is used in `contentview.py` in `view`.  Hope this helps!

2022-07-11 23:03 UTC, latran commented
So something strange is happening here https://github.com/SatelliteQE/airgun/blob/master/airgun/entities/product.py#L209.  Automation hit this portion, but the selection of the element in the table is not being registered.  Weirdly, if you run `test_positive_bulk_action_advanced_sync` with just `session.product.advanced_sync([product.name], sync_type='optimized')` for https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_product.py#L175,  it's able to recognize and select it correctly.  I'm baffled as to why that is.
@omkarkhatavkar can you take a look and see?

2022-07-12 11:41 UTC, omkarkhatavkar commented
> So something strange is happening here https://github.com/SatelliteQE/airgun/blob/master/airgun/entities/product.py#L209. Automation hit this portion, but the selection of the element in the table is not being registered. Weirdly, if you run `test_positive_bulk_action_advanced_sync` with just `session.product.advanced_sync([product.name], sync_type='optimized')` for https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_product.py#L175, it's able to recognize and select it correctly. I'm baffled as to why that is. @omkarkhatavkar can you take a look and see?

It's not usual behavior from the selenium end. Some time selenium fails to perform actions on the ng (angular) object. Not pretty sure why this happen but I have solution for this here https://github.com/SatelliteQE/airgun/pull/722

2022-07-13 19:59 UTC, Griffin-Sullivan commented on airgun/entities/product.py
> +        return view.read()
```def verify_content_checksum(self, entities_list):
        """Verify content checksum for product
        """

        view = self.navigate_to(
            self,
            'Select Action',
            action_name='Verify Content Checksum',
            entities_list=entities_list,
        )
        view.task_alert.click()
        view = TaskDetailsView(view.browser)
        view.wait_for_result()
        return view.read()
```

2022-07-13 19:59 UTC, Griffin-Sullivan commented on airgun/entities/product.py
> +        return view.read()
```suggestion
    def verify_content_checksum(self, entities_list):
        """Verify content checksum for product
        """

        view = self.navigate_to(
            self,
            'Select Action',
            action_name='Verify Content Checksum',
            entities_list=entities_list,
        )
        view.task_alert.click()
        view = TaskDetailsView(view.browser)
        view.wait_for_result()
        return view.read()
```

2022-07-13 20:01 UTC, Griffin-Sullivan commented on airgun/views/product.py
> +        return self.browser.wait_for_element(self.title, exception=False) is not None
```suggestion
class ProductVerifyContentChecksum(BaseLoggedInView):
    """Represents Advanced Sync page for Products."""

    task_alert = Text("//a[normalize-space(.)='Click to monitor task progress.']")

    @property
    def is_displayed(self):
        return self.browser.wait_for_element(self.title, exception=False) is not None 
```
This is just targeting the button in the alert. I'm guessing someone has already written a view for this that we can steal.

2022-07-14 17:46 UTC, Griffin-Sullivan approved these changes

2022-07-15 06:33 UTC, jyejare requested changes

2022-07-15 06:33 UTC, jyejare commented on airgun/views/product.py
> +        return self.browser.wait_for_element(self.title, exception=False) is not None
```suggestion
        return self.browser.wait_for_element(self.task_alert, exception=False) is not None
```

2022-07-15 18:16 UTC, jyejare approved these changes

2022-07-15 21:22 UTC, latran approved these changes
Selection issue has been resolved.  Giving my ACK

2022-07-18 08:15 UTC, omkarkhatavkar approved these changes
ACK

2022-07-18 08:15 UTC, merged