updating the airgun autocherrypick n-1 version as robottelo
SatelliteQE/airgun pull request #748
Opened 2022-09-08 13:10 UTC by omkarkhatavkar

applying same as https://github.com/SatelliteQE/robottelo/pull/10015

2022-09-08 14:26 UTC, jyejare approved these changes

2022-09-08 17:37 UTC, ogajduse approved these changes

2022-09-08 23:44 UTC, latran approved these changes

2022-09-13 10:53 UTC, peterdragun requested changes
Please update PR, same as SatelliteQE/robottelo/pull/10044

2022-09-14 12:23 UTC, peterdragun approved these changes

2022-09-14 12:25 UTC, merged