Fix locator for hosts table
SatelliteQE/airgun pull request #811
Opened 2023-02-20 09:36 UTC by LadislavVasina1

Test `test_positive_read_details_page_from_new_ui` is failing in the 6.13 automation.
The test was trying to click hostname in the  Hosts table but it was actually clicking on the Actions dropdown in the same row.
Locator change fixes the test failure.
Tested locally.
![image](https://user-images.githubusercontent.com/62888716/220067746-fe20a6a1-5b4c-4ab7-bed0-d59967eaa261.png)

2023-02-21 05:58 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: -k test_positive_read_details_page_from_new_ui  tests/foreman/ui/test_host.py

2023-02-21 05:59 UTC, omkarkhatavkar approved these changes

2023-02-21 07:10 UTC, shweta83 requested changes

2023-02-21 07:10 UTC, shweta83 commented on airgun/views/host.py
> +            'Name': Text('//*[@id="content"]/table/tbody/tr/td[5]/a'),
Can we try a better locator?Something like 
'Name': Text("//a[contains(@href, '/new/hosts')]")

2023-02-21 07:49 UTC, shweta83 commented on airgun/views/host.py
> +            'Name': Text('//*[@id="content"]/table/tbody/tr/td[5]/a'),
```suggestion
           'Name': Text("//a[contains(@href, '/new/hosts')]"),
```

2023-02-21 08:02 UTC, LadislavVasina1 commented
trigger: test-robottelo
pytest: -k test_positive_read_details_page_from_new_ui tests/foreman/ui/test_host.py

2023-02-21 08:34 UTC, LadislavVasina1 commented on airgun/views/host.py
> +            'Name': Text('//*[@id="content"]/table/tbody/tr/td[5]/a'),
Thanks for the suggestion, working now.

2023-02-21 08:38 UTC, vsedmik approved these changes

2023-02-21 09:49 UTC, merged

2023-02-23 12:23 UTC, LadislavVasina1 commented
trigger: test-robottelo
pytest: -k test_positive_assign_taxonomies tests/foreman/ui/test_host.py